(provide 'dp-programing)

(require 'dp-csharp)
(require 'dp-markdown)
(require 'dp-org)
(require 'dp-javascript)
(require 'dp-php)
(require 'dp-nxml)
(require 'dp-css)
(require 'dp-haml)
(require 'dp-sql)
(require 'dp-geben)

(require 'dp-paredit)
(require 'dp-haskell)
(require 'dp-elisp)
(require 'dp-slime)
(require 'dp-clojure)
(require 'dp-cl)
