(provide 'dp-programing)
(require-package 'electric-spacing)
(require-package 'lsp-mode)

(require 'lsp-mode)
;(add-hook 'java-mode-hook #'lsp)
;(add-hook 'js-mode-hook #'lsp)

(which-function-mode 1)
(require 'dp-csharp)
(require 'dp-markdown)
(require 'dp-org)
(require 'dp-javascript)
(require 'dp-php)
(require 'dp-nxml)
(require 'dp-css)
(require 'dp-haml)
(require 'dp-web)
(require 'dp-sql)
(require 'dp-geben)

(require 'dp-paredit)
(require 'dp-haskell)
(require 'dp-elisp)
(require 'dp-slime)
(require 'dp-clojure)
(require 'dp-cl)
(require 'dp-java)
(require 'dp-solidity)

(require 'dp-http)
(require 'dp-yaml)

